version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"
  secrets-manager:
    GITHUB_TOKEN: "mygithub-token"

phases:
  install:
    commands:
      - echo installing maven...
      - sudo yum update -y
      - sudo yum install -y maven

  build:
    commands:
      - echo building the justiceleague-tracker
      - echo "GitHub Token Loaded Successfully"

artifacts:
  files:
    - appspec.yml
  discard-paths: yes
